### ISSUE TITLE
Molecular Transformator does not show recipes in REI in IC2Classic Advanced Solar Panels addon.

### ISSUE THREAD

**Issue by NeoFolia** [CrossVas/REIAddonsIC2Classic#3]
Molecular Transformator does not show recipes in REI in IC2 Classic Advanced Solar Panels addon.
![image](https://github.com/CrossVas/REIAddonsIC2Classic/assets/147491823/afd6dd7f-b745-432d-a909-6f922fdbcbaf)

**Comment by CrossVas** [comment]
This is something ASP should provide.
I've submitted a pull request to [ASP](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition) adding REI compat

The PR can be found [here](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/pull/19)
