### ISSUE TITLE
The icons of items that should be in the molecular transformator recipe are not visible.

### ISSUE THREAD

**Issue by NeoFolia** [CrossVas/REIAddonsIC2Classic#4]
The icons of items that should be in the molecular transformator recipe are not visible.

![image](https://github.com/CrossVas/REIAddonsIC2Classic/assets/147491823/b10dd35b-20c4-40c6-b423-e546beaf227c)

**Comment by NeoFolia** [comment]
or is it extra spaces?

**Comment by CrossVas** [comment]
This is not a REIAddons issue.
I fact this isn't an issue at all.
Items are displayed on the left side of the recipe display.

**Comment by CrossVas** [comment]
@kitovoi111 just checked. 
There are no extra spaces, meaning your setup is broken or you're trying to fool me.
![image](https://github.com/CrossVas/REIAddonsIC2Classic/assets/25727222/803cf2ff-cac9-45bf-9096-fc665df12182)
